apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-node-tagger

# clusterrole for k8s-node-tagger to read/watch nodes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-node-tagger
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-node-tagger
subjects:
  - kind: ServiceAccount
    name: k8s-node-tagger
    namespace: k8s-node-tagger
roleRef:
  kind: ClusterRole
  name: k8s-node-tagger
  apiGroup: rbac.authorization.k8s.io

# namespace role for k8s-node-tagger to use the lease API. Shouldn't be needed if leader election is disabled.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-node-tagger
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-node-tagger
subjects:
  - kind: ServiceAccount
    name: k8s-node-tagger
    namespace: k8s-node-tagger
roleRef:
  kind: Role
  name: k8s-node-tagger
  apiGroup: rbac.authorization.k8s.io
